#!/usr/bin/env bash
# install load balancer
apt-get update -y
apt-get install software-properties-common -y
apt-get update -y
echo | add-apt-repository ppa:vbernat/haproxy-2.0
apt-get update -y
apt-get install haproxy=2.0.\* -y
FEND="\nfrontend haproxynode\n\tbind *:80\n\tmode http\n\tdefault_backend backendnodes\n"
echo -e "$FEND" >> /etc/haproxy/haproxy.cfg
BEND="backend backendnodes\n\tbalance roundrobin\n\tserver 462927-web-01 54.84.61.95:80 check\n\tserver 462927-web-02 54.89.45.44:80 check\n"
echo -e "$BEND" >> /etc/haproxy/haproxy.cfg
sed -ie 's/\sssl.*//' /etc/haproxy/haproxy.cfg
service haproxy start

